{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-msqc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MSQC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MSQC/MSQC_{{ version }}.tar.gz
  sha256: 8e5c43c57d6bbd2399cb83a7e6c7039cd6157bd24ef097a21ea1a06141393ac7

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}      # [build_platform != target_platform]
    - {{ posix }}zip                 # [win]
    - xorg-libxfixes                 # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - r-base
    - r-rgl
  run:
    - r-base
    - r-rgl

test:
  commands:
    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib $R -e "library('MSQC')"  # [not win]
    - "\"%R%\" -e \"library('MSQC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MSQC
  license: GPL-2.0-or-later
  summary: This is a toolkit for multivariate process monitoring. It computes several multivariate control charts e.g. Hotelling, Chi-squared, MEWMA, MCUSUM and Generalized Variance. Ten didactic datasets are included. It includes some techniques for assessing multivariate normality e.g. Mardia's, Royston's and Henze-Zirkler's
    tests. Please, see the NEWS file for the latest changes in the package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: MSQC
# Type: Package
# Title: Multivariate Statistical Quality Control
# Version: 1.0.2
# Date: 2016-05-30
# Author: Edgar Santos-Fernandez <edgar.santosfdez@gmail.com>
# Maintainer: Edgar Santos-Fernandez <edgar.santosfdez@gmail.com>
# Depends: R (>= 3.1.0), graphics, stats, utils
# Imports: rgl
# Description: This is a toolkit for multivariate process monitoring. It computes several multivariate control charts e.g. Hotelling, Chi-squared, MEWMA, MCUSUM and Generalized Variance. Ten didactic datasets are included. It includes some techniques for assessing multivariate normality e.g. Mardia's, Royston's and Henze-Zirkler's tests. Please, see the NEWS file for the latest changes in the package.
# License: GPL-2 | GPL-3
# LazyLoad: yes
# Repository: CRAN
# NeedsCompilation: no
# Packaged: 2016-05-31 23:24:13 UTC; esantosf
# Date/Publication: 2016-06-01 07:39:37
